-- ============================

-- This file was created using Derby's dblook utility.
-- Timestamp: 2017-05-21 16:57:27.801
-- Source database is: kiraju
-- Connection URL is: jdbc:derby://localhost:1527/kiraju;user=APP;password=password
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for schemas
-- ----------------------------------------------

-- CREATE SCHEMA "APP";

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "APP"."MEJA" ("ID" SMALLINT NOT NULL, "STATUS" SMALLINT, "NOMOR" VARCHAR(10));

CREATE TABLE "APP"."PESAN" ("ID" INTEGER NOT NULL, "TRANSAKSI_ID" INTEGER, "MENU_ID" SMALLINT, "JUMLAH" SMALLINT);

CREATE TABLE "APP"."PENGELUARAN" ("ID" INTEGER NOT NULL, "NAMA" VARCHAR(100), "HARGA" INTEGER, "DT_ONLY" DATE);

CREATE TABLE "APP"."POSISI" ("ID" SMALLINT NOT NULL, "NAMA" VARCHAR(20));

CREATE TABLE "APP"."MENU" ("ID" SMALLINT NOT NULL, "NAMA" VARCHAR(50), "HARGA" INTEGER, "CREATED_DT" TIMESTAMP, "UPDATED_DT" TIMESTAMP, "JENIS" SMALLINT, "DELETED_FLAG" SMALLINT DEFAULT 0);

CREATE TABLE "APP"."JENIS_MENU" ("ID" SMALLINT NOT NULL, "NAMA" VARCHAR(50), "DELETED_FLAG" SMALLINT DEFAULT 0);

CREATE TABLE "APP"."TRANSAKSI" ("ID" INTEGER NOT NULL, "MEJA_ID" SMALLINT, "DT_START" TIMESTAMP, "DT_END" TIMESTAMP, "TOTAL" INTEGER, "STATUS" SMALLINT, "NAMA_PEMESAN" VARCHAR(20), "USER_START" SMALLINT, "USER_END" SMALLINT, "END_DT_ONLY" DATE, "END_TIME_ONLY" TIME);

CREATE TABLE "APP"."USERS" ("ID" SMALLINT NOT NULL, "NAMA" VARCHAR(50), "USERNAME" VARCHAR(20), "PASSWORD" VARCHAR(20), "POSISI_ID" SMALLINT, "DELETED_FLAG" SMALLINT DEFAULT 0);

CREATE TABLE "APP"."GENERAL" ("INSTALL_DT" DATE);

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "APP"."JENIS_MENU" ADD CONSTRAINT "SQL170316221656440" PRIMARY KEY ("ID");

ALTER TABLE "APP"."JENIS_MENU" ADD CONSTRAINT "SQL170517113047160" UNIQUE ("NAMA");

ALTER TABLE "APP"."PESAN" ADD CONSTRAINT "SQL170323150710160" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MEJA" ADD CONSTRAINT "SQL170323142715180" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MEJA" ADD CONSTRAINT "SQL170517111109090" UNIQUE ("NOMOR");

ALTER TABLE "APP"."PENGELUARAN" ADD CONSTRAINT "SQL170430152147750" PRIMARY KEY ("ID");

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "SQL170327183212990" PRIMARY KEY ("ID");

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "SQL170517113152910" UNIQUE ("USERNAME");

ALTER TABLE "APP"."TRANSAKSI" ADD CONSTRAINT "SQL170323145838390" PRIMARY KEY ("ID");

ALTER TABLE "APP"."POSISI" ADD CONSTRAINT "SQL170327183251020" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU" ADD CONSTRAINT "SQL170508113557820" PRIMARY KEY ("ID");

-- FOREIGN
ALTER TABLE "APP"."PESAN" ADD CONSTRAINT "FK_TRANSAKSI" FOREIGN KEY ("TRANSAKSI_ID") REFERENCES "APP"."TRANSAKSI" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PESAN" ADD CONSTRAINT "FK_MENU" FOREIGN KEY ("MENU_ID") REFERENCES "APP"."MENU" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "FK_POSISI_ID" FOREIGN KEY ("POSISI_ID") REFERENCES "APP"."POSISI" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSAKSI" ADD CONSTRAINT "FK_MEJA" FOREIGN KEY ("MEJA_ID") REFERENCES "APP"."MEJA" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSAKSI" ADD CONSTRAINT "FK_USERSTART" FOREIGN KEY ("USER_START") REFERENCES "APP"."USERS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSAKSI" ADD CONSTRAINT "FK_USEREND" FOREIGN KEY ("USER_END") REFERENCES "APP"."USERS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

---------------------------
-- DML STATEMENT FOR POSISI
---------------------------
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (1, 'Hidden User');
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (2, 'Super User');
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (3, 'Tanpa User');
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (4, 'Administrator');
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (5, 'Kasir');

---------------------------
-- DML STATEMENT FOR USERS
---------------------------
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, DELETED_FLAG) 
	VALUES (1, 'Hidden User', 'sondok', 'p@ssw0rd123', 1, 0);
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, DELETED_FLAG) 
	VALUES (2, 'Super User', 'su', 'password', 2, 0);
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, DELETED_FLAG) 
	VALUES (3, 'Tanpa User', 'kiraju', 'password', 3, 0);
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, DELETED_FLAG) 
	VALUES (4, 'Admin', 'adm', 'password', 4, 0);
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, DELETED_FLAG) 
	VALUES (5, 'Kasir', 'ksr', 'password', 5, 0);

---------------------------
-- DML STATEMENT FOR MEJA
---------------------------
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (0, 1, '0');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (1, 0, '1');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (2, 0, '2');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (3, 0, '3');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (4, 0, '4');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (5, 0, '5');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (6, 0, '6');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (7, 0, '7');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (8, 0, '8');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (9, 0, '9');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (10, 0, '10');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (11, 0, '11');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (12, 0, '12');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (13, 0, '13');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (14, 0, '14');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (15, 0, '15');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (16, 0, '16');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (17, 0, '17');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (18, 0, '18');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (19, 0, '19');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (20, 0, '20');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (21, 0, '21');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (22, 0, '22');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (23, 0, '23');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (24, 0, '24');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (25, 0, '25');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (26, 0, '26');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (27, 0, '27');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (28, 0, '28');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (29, 0, '29');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (30, 0, '30');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (31, 0, '31');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (32, 0, '32');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (33, 0, '33');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (34, 0, '34');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (35, 0, '35');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (36, 0, '36');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (37, 0, '37');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (38, 0, '38');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (39, 0, '39');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (40, 0, '40');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (41, 0, '41');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (42, 0, '42');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (43, 0, '43');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (44, 0, '44');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (45, 0, '45');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (46, 0, '46');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (47, 0, '47');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (48, 0, '48');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (49, 0, '49');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (50, 0, '50');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (51, 0, '51');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (52, 0, '52');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (53, 0, '53');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (54, 0, '54');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (55, 0, '55');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (56, 0, '56');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (57, 0, '57');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (58, 0, '58');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (59, 0, '59');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (60, 0, '60');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (61, 0, '61');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (62, 0, '62');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (63, 0, '63');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (64, 0, '64');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (65, 0, '65');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (66, 0, '66');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (67, 0, '67');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (68, 0, '68');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (69, 0, '69');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (70, 0, '70');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (71, 0, '71');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (72, 0, '72');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (73, 0, '73');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (74, 0, '74');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (75, 0, '75');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (76, 0, '76');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (77, 0, '77');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (78, 0, '78');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (79, 0, '79');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (80, 0, '80');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (81, 0, '81');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (82, 0, '82');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (83, 0, '83');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (84, 0, '84');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (85, 0, '85');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (86, 0, '86');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (87, 0, '87');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (88, 0, '88');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (89, 0, '89');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (90, 0, '90');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (91, 0, '91');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (92, 0, '92');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (93, 0, '93');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (94, 0, '94');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (95, 0, '95');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (96, 0, '96');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (97, 0, '97');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (98, 0, '98');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (99, 0, '99');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (100, 0, '100');
--20170812 - V1.1
-- INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
-- 	VALUES (101, 0, '101');
-- INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
-- 	VALUES (102, 0, '102');
-- INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
-- 	VALUES (103, 0, '103');
-- INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
-- 	VALUES (104, 0, '104');
