package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1



/**
 * JenisMenu generated by hbm2java
 */
public class JenisMenu  implements java.io.Serializable {


     private short id;
     private String nama;
     private Short deletedFlag;

    public JenisMenu() {
    }

    public JenisMenu(String nama, Short deletedFlag) {
       this.nama = nama;
       this.deletedFlag = deletedFlag;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Short getDeletedFlag() {
        return this.deletedFlag;
    }
    
    public void setDeletedFlag(Short deletedFlag) {
        this.deletedFlag = deletedFlag;
    }




}


