package kiraju.model;
// Generated Mar 29, 2018 3:23:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PembayaranHutang generated by hbm2java
 */
public class PembayaranHutang  implements java.io.Serializable {


     private int id;
     private Date tanggal;
     private Integer total;
     private TransaksiPembelian trxPembelianId;
     private MetodePembayaran mtdByrId;

    public PembayaranHutang() {
    }

	
    public PembayaranHutang(int id) {
        this.id = id;
    }
    public PembayaranHutang(int id, Date tanggal, Integer total, TransaksiPembelian trxPembelianId, MetodePembayaran mtdByrId) {
       this.id = id;
       this.tanggal = tanggal;
       this.total = total;
       this.trxPembelianId = trxPembelianId;
       this.mtdByrId = mtdByrId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }
    public TransaksiPembelian getTrxPembelianId() {
        return this.trxPembelianId;
    }
    
    public void setTrxPembelianId(TransaksiPembelian trxPembelianId) {
        this.trxPembelianId = trxPembelianId;
    }
    public MetodePembayaran getMtdByrId() {
        return this.mtdByrId;
    }
    
    public void setMtdByrId(MetodePembayaran mtdByrId) {
        this.mtdByrId = mtdByrId;
    }




}


