package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1



/**
 * Pesan generated by hbm2java
 */
public class Pesan  implements java.io.Serializable {


     private int id;
     private Transaksi transaksiId;
     private Menu menuId;
     private Short jumlah;

    public Pesan() {
    }

	
    public Pesan(Transaksi transaksiId, Menu menuId) {
        this.transaksiId = transaksiId;
        this.menuId = menuId;
    }
    public Pesan(Transaksi transaksiId, Menu menuId, Short jumlah) {
       this.transaksiId = transaksiId;
       this.menuId = menuId;
       this.jumlah = jumlah;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Transaksi getTransaksiId() {
        return this.transaksiId;
    }
    
    public void setTransaksiId(Transaksi transaksiId) {
        this.transaksiId = transaksiId;
    }
    public Menu getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Menu menuId) {
        this.menuId = menuId;
    }
    public Short getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(Short jumlah) {
        this.jumlah = jumlah;
    }




}


