package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1



/**
 * Posisi generated by hbm2java
 */
public class Posisi  implements java.io.Serializable {


     private short id;
     private String nama;

    public Posisi() {
    }

	
    public Posisi(short id) {
        this.id = id;
    }
    public Posisi(short id, String nama) {
       this.id = id;
       this.nama = nama;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


