package kiraju.model;
// Generated Mar 29, 2018 3:23:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TransaksiPembelian generated by hbm2java
 */
public class TransaksiPembelian  implements java.io.Serializable {


     private int id;
     private Date tanggal;
     private Integer total;
     private Pemasok pemasokId;
     private MetodePembayaran mtdByrId;
     private Boolean isLunas;
     private Set<DaftarPembelian> daftarPembelian = new HashSet<>(0);
     private Boolean status;

    public TransaksiPembelian() {
    }

	
    public TransaksiPembelian(int id) {
        this.id = id;
    }
    public TransaksiPembelian(int id, Date tanggal, Integer total, Pemasok pemasokId, MetodePembayaran mtdByrId, Boolean isLunas) {
       this.id = id;
       this.tanggal = tanggal;
       this.total = total;
       this.pemasokId = pemasokId;
       this.mtdByrId = mtdByrId;
       this.isLunas = isLunas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }
    public Pemasok getPemasokId() {
        return this.pemasokId;
    }
    
    public void setPemasokId(Pemasok pemasokId) {
        this.pemasokId = pemasokId;
    }
    public MetodePembayaran getMtdByrId() {
        return this.mtdByrId;
    }
    
    public void setMtdByrId(MetodePembayaran mtdByrId) {
        this.mtdByrId = mtdByrId;
    }
    public Boolean getIsLunas() {
        return this.isLunas;
    }
    
    public void setIsLunas(Boolean isLunas) {
        this.isLunas = isLunas;
    }

    public Set<DaftarPembelian> getDaftarPembelian() {
        return daftarPembelian;
    }

    public void setDaftarPembelian(Set<DaftarPembelian> daftarPembelian) {
        this.daftarPembelian = daftarPembelian;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }




}


