package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private short id;
     private String nama;
     private String username;
     private String password;
     private Posisi posisiId;
     private Short deletedFlag;

    public Users() {
    }

    public Users(String nama, String username, String password, Posisi posisiId, Short deletedFlag) {
       this.nama = nama;
       this.username = username;
       this.password = password;
       this.posisiId = posisiId;
       this.deletedFlag = deletedFlag;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Posisi getPosisiId() {
        return this.posisiId;
    }
    
    public void setPosisiId(Posisi posisiId) {
        this.posisiId = posisiId;
    }
    public Short getDeletedFlag() {
        return this.deletedFlag;
    }
    
    public void setDeletedFlag(Short deletedFlag) {
        this.deletedFlag = deletedFlag;
    }




}


